version: '3.8'

services:
  # Frontend (React + Vite)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5175:5175"
    environment:
      - VITE_API_BASE_URL=http://topteamfight.test:3001/api
      - VITE_APP_HOSTNAME=topteamfight.test
    extra_hosts:
      - "topteamfight.test:host-gateway"
      - "www.topteamfight.test:host-gateway"
    depends_on:
      - backend
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    networks:
      - studio-network

  # Backend (Node.js + Express)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRES_IN=7d
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=your-email@gmail.com
      - EMAIL_PASS=your-app-password
      - BCRYPT_ROUNDS=12
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - FRONTEND_URL=http://topteamfight.test:5175
      - API_BASE_URL=http://topteamfight.test:3001/api
    volumes:
      - ./backend/src:/app/src
      - ./backend/uploads:/app/uploads
      - ./backend/prisma:/app/prisma
    networks:
      - studio-network

networks:
  studio-network:
    driver: bridge

volumes:
  uploads: 